# frozen_string_literal: true

Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

# check_docs.rb - guards against drift between little/ chapter code and milestone snapshots.
#
# How it works:
#   Each line of a ```text block tagged with <!-- run: examples/partN.rb --> must appear
#   in the actual output of partN.rb run against dist/partN/lib (subset match).
#   dist/ is bundled inside examples/ (generated by `make impls`).
#
# Run (self-contained within the examples/ directory):
#   ruby check_docs.rb
#   ruby check_docs.rb --fix   # overwrite text blocks with actual output
#
# Zero dependencies, stdlib only.

HERE    = __dir__
LITTLE  = File.expand_path('..', HERE)
FIX     = ARGV.include?('--fix')

CHAPTERS = Dir[File.join(LITTLE, 'part*.md')].sort
  .reject { |f| File.basename(f).start_with?('_') }

EXAMPLES = Dir[File.join(HERE, 'part*.rb')].sort

# Extract the "# region <id> … # endregion" span (excluding the marker lines).
def extract_region(file, id)
  lines = File.readlines(file, chomp: true)
  s = lines.index { |l| l.strip == "# region #{id}" }
  return nil unless s

  e = (s + 1...lines.size).find { |i| lines[i].strip == '# endregion' }
  return nil unless e

  lines[(s + 1)...e].map(&:rstrip)
end

# Resolve a path relative to examples/.
def resolve_path(path_str)
  File.join(HERE, path_str)
end

# Run an example and capture its output. The load path is derived from impls/dist/partN/lib.
def run_example(example_path)
  # Run as-is, honoring the file's own $LOAD_PATH setup.
  out = `ruby "#{example_path}" 2>&1`
  [out, $?.success?]
end

problems = []
fixed    = 0

# --- Is each example green on its own? + cache its output ---------------------
outputs = {}
EXAMPLES.each do |path|
  out, ok = run_example(path)
  outputs[File.basename(path)] = out
  problems << "example not green: #{File.basename(path)}" unless ok
end

# --- Check the run: directives per chapter -----------------------------------
CHAPTERS.each do |md|
  lines = File.readlines(md, chomp: true)
  i = 0
  while i < lines.size
    m = lines[i].match(/<!--\s*(run|include):\s*([^\s#]+)(?:#(\S+))?\s*-->/)
    unless m
      i += 1
      next
    end
    kind   = m[1]
    path   = m[2]
    region = m[3]
    src    = resolve_path(path)

    open_idx  = (i + 1...lines.size).find { |j| lines[j].start_with?('```') }
    close_idx = open_idx && (open_idx + 1...lines.size).find { |j| lines[j].strip == '```' }
    unless open_idx && close_idx
      problems << "#{File.basename(md)}: no closed ``` block after the directive (#{path})"
      i += 1
      next
    end
    body  = lines[(open_idx + 1)...close_idx].map(&:rstrip)
    label = "#{File.basename(md)} [#{kind}: #{path}#{"##{region}" if region}]"

    if kind == 'include'
      want = extract_region(src, region)
      if want.nil?
        problems << "#{label}: region '#{region}' not found in #{path}"
      elsif body != want
        if FIX
          lines[(open_idx + 1)...close_idx] = want
          File.write(md, "#{lines.join("\n")}\n")
          fixed += 1
        else
          problems << "#{label}: prose code differs from region (sync with --fix)"
        end
      end
    else # run
      out = outputs[File.basename(src)]
      if out.nil?
        problems << "#{label}: #{File.basename(src)} not found in examples/"
      else
        out_lines = out.lines.map(&:chomp)
        missing = body.reject(&:empty?).reject { |l| out_lines.include?(l) }
        problems << "#{label}: lines not in output: #{missing.inspect}" unless missing.empty?
      end
    end
    i = close_idx + 1
  end
end

puts "synced #{fixed} include block(s) from regions." if FIX && fixed.positive?

if problems.empty?
  puts "OK: v2/ja/little/ code/output is in sync with milestone snapshots (chapters: #{CHAPTERS.size}, examples: #{EXAMPLES.size})."
  exit 0
else
  warn 'DRIFT detected:'
  problems.each { |p| warn "  - #{p}" }
  exit 1
end
